# Generated by Django 5.1.2 on 2024-10-31 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_categoria_remove_livros_cartegoria_livros_categoria'),
        ('usuarios', '0002_alter_usuarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='usuario',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios'),
            preserve_default=False,
        ),
    ]
