# Generated by Django 5.1.2 on 2024-10-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_alter_emprestimos_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
    ]
