# Generated by Django 5.1.2 on 2024-11-01 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0008_remove_emprestimos_tempo_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='emprestado',
        ),
    ]
