# Generated by Django 5.1.2 on 2024-11-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_remove_livros_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
