# Generated by Django 5.1.2 on 2024-11-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0011_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='devolvido',
            field=models.BooleanField(default=False),
        ),
    ]
