# Generated by Django 5.1.2 on 2024-11-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0012_emprestimos_devolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livro'),
        ),
    ]
