# Generated by Django 5.1.2 on 2024-11-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0013_livros_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='img',
        ),
        migrations.AddField(
            model_name='livros',
            name='img_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
