# Generated by Django 5.1.2 on 2024-11-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='endereco',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
